#!/usr/bin/env sh
set -e

git diff --cached --diff-filter=ACMR --name-only -z |
  xargs -0 -r sh -c '
    set -e
    bun run eslint --cache --fix --no-warn-ignored -- "$@"
    bun run prettier --cache --ignore-unknown --write -- "$@"
    git add -- "$@"
  ' sh
